[page]
title = "Code Vulnerability Analyzer (CVA)"
description = "CVA is SAP’s static code analyser. It helps you to identify and fix security vulnerabilities in your ABAP coding."
reason = "Secure coding is a must. The tool from SAP for checking code for security issues is CVA. Problem: the price makes it rather unlikely it is used by customers."
support = "Supported"

[links]
"Code Vulnerability Analyzer Checks" = "https://community.sap.com/t5/application-development-blog-posts/code-vulnerability-analyzer-checks/ba-p/13339467"
"Code Vulnerability Analyzer" = "https://www.sap.com/documents/2018/11/ec5d12c6-287d-0010-87a3-c30de2ffd8ff.html"
"CVA DAQ" = "https://community.sap.com/t5/application-development-blog-posts/sap-code-vulnerability-analyzer-cva-faqs/ba-p/13486106"

[config]
label = "CVA"
ring = "ADOPT"
quadrant = "Tools"
active = true
moved = 0
