[page]
title = "ABAP Cloud"
description = "ABAP Cloud is the new ABAP development model, not a product.<br/><br/>ABAP Cloud <br/><br/>- is the ABAP development model to build cloud-ready business apps, services, and extensions.<br/><br/>- comes with SAP BTP and SAP S/4HANA.<br/><br/>- works with public or private cloud, and even on-premise."
reason = "Recommended for new development in S/4HANA"
support = "Supported"

[links]
"SCN" = "https://community.sap.com/t5/enterprise-resource-planning-blogs-by-sap/abap-cloud/ba-p/13557273"
"Extensibility Guide" = "https://www.sap.com/documents/2022/10/52e0cd9b-497e-0010-bca6-c68f7e60039b.html"

[config]
label = "ABAP Cloud"
ring = "ADOPT"
quadrant = "Frameworks"
active = true
moved = 0
