[page]
title = "Clean ABAP"
description = "ABAP Unit is a unit-testing framework that is integrated into the ABAP language.<br/><br/>In unit testing, a developer ensures that the correct behavior of the smallest testable units – such as the methods of classes – of his or her code is verifiable. Unit testing makes it easier to verify quality, to refactor code, to perform regression testing, and to implement according to the test-driven development model."
reason = "The way to do unit testing in ABAP"
support = "Supported"

[links]
"Homepage" = "https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md"
"Blog: ABAP Tools for Clean ABAP" = "https://community.sap.com/t5/technology-blogs-by-sap/abap-tools-for-clean-abap/ba-p/13577378"

[config]
label = "Clean ABAP"
ring = "USE"
quadrant = "Frameworks"
active = true
moved = 0
