[page]
title = "Custom Fields and Logic"
description = "With the extensibility apps, you can create custom fields, data source extensions, and enhancement implementations for specific business contexts to enhance predelivered applications that are extensible, in order to adapt them to your business needs.<br/><br/>You can also create custom CDS views based on predelivered data sources. The data of an application is distributed across several database tables. Using CDS views, you can merge the data from different data sources and rearrange the table fields according to application-specific needs.<br/><br/>It is possible to create custom business objects with UIs and add custom logic to custom business objects. Thus, you can create your own applications based on custom business objects."
reason = "Recommended way to adjust UI and add new fields to S/4HANA Fiori Apps. <br/><br/>Business expert can use the Custom Fields app to create your own fields and the Custom Logic app to create own implementations to customize applications and their UIs, reports, email templates, and form templates.<br/><br/>Modifications are upgrade safe."
support = "Supported."

[links]
"SAP Help" = "https://help.sap.com/docs/SAP_S4HANA_CLOUD/0f69f8fb28ac4bf48d2b57b9637e81fa/57909455bf7c4fdd8bcf48d76c1eae33.html?locale=en-US"
"SAP Learning" = "https://learning.sap.com/learning-journeys/get-started-with-in-app-extensibility-in-sap-s-4hana/using-custom-fields-and-logic_c3abf136-f83f-475d-95e0-2d21d699d890"
"Fiori App Library" = "https://fioriappslibrary.hana.ondemand.com/sap/fix/externalViewer/#/detail/Apps('F1481')/S27OP"

[config]
label = "Custom Fields & Logic"
ring = "USE"
quadrant = "Frameworks"
active = true
moved = 0
