[page]
title = "ABAP RESTful Application Programming Model managed draft"
description = "Based on the implementation type managed with draft of the ABAP RESTful Application Programming Model using UUID keys.<br/><br/>There is no legacy business application logic involved.<br/><br/>Benefit from the lightweight BO standard implementation of the managed implementation type, in which the RAP managed runtime framework assumes an extensive part of the standard implementation with out-of-the-box support for create, update, and delete.<br/><br/>In addition, you may need to provide the end user with capabilities to store changed data in the backend at any time and proceed at a later point in time, or to recover such data from a different device, even if the application client has terminated unexpectedly. This use case is supported by the draft concept of the ABAP RESTful Application Programming Model. Draft-enabled business objects persist the state of the transactional buffer after every transaction on a designated draft database table. This allows the end user to stop and continue work processes at any point in time, even with inconsistent data."
reason = "Create a completely new transactional app for a Fiori Elements UI following the greenfield approach"
support = "Supported"

[links]
"SAP Help" = "https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/289477a81eec4d4e84c0302fb6835035.html"
Documentation = "https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/71ba2bec1d0d4f22bc344bba6b569f2e.html"

[config]
label = "RAP managed draft"
ring = "ADOPT"
quadrant = "Frameworks"
active = true
moved = 0
