[page]
title = "ABAP RESTful Application Programming Model managed"
description = "New applications can highly benefit from out-of-the-box support for transactional processing. Standard operations (create, update, delete) must only be specified in the behavior definition to obtain a ready-to-run business object. In addition the provisioning and handling of the transactional buffer is automatically done for you. The technical implementation aspects are taken over by the managed RAP BO provider. The interaction phase and the save sequence are implemented generically. The application developer can then focus on business logic that is implemented using actions, validations and determinations and user interaction. The corresponding transactional engine manages the entire life cycle of your business object and covers all aspects of your business application development."
reason = "Recommended for new development"
support = "Supported"

[links]
"SAP Help" = "https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/289477a81eec4d4e84c0302fb6835035.html"
"Documentation" = "https://help.sap.com/docs/ABAP_PLATFORM_NEW/fc4c71aa50014fd1b43721701471913d/b5bba99612cf4637a8b72a3fc82c22d9.html"

[config]
label = "RAP managed"
ring = "USE"
quadrant = "Frameworks"
active = true
moved = 0
