[page]
title = "BTP"
description = "SAP BTP brings together application development, automation, data management, analytics, planning, integration, and AI into a single platform."
reason = "Currently the recommended cloud from SAP."
support = "Supported"

[links]
SAP = "https://www.sap.com/products/technology-platform/what-is-sap-business-technology-platform.html"
"Discovery Center" = "https://discovery-center.cloud.sap/index.html"

[config]
label = "BTP"
ring = "ADOPT"
quadrant = "Technology"
active = true
moved = 0