[page]
title = "OData v2"
description = "Open Data Protocol (OData) is an open protocol that allows the creation and consumption of queryable and interoperable Web service APIs in a standard way. Widely supported by SAP solutions."
reason = "Recommended for SEGW projects. For RAP: OData v4 is recommended."
support = "Supported"

[links]
OData = "https://www.odata.org/"
"OData Vocabularies" = "https://sap.github.io/odata-vocabularies/docs/v2-annotations.html"
"OData v2 Standard" = "https://www.odata.org/documentation/odata-version-2-0/"
Blog = "https://community.sap.com/t5/technology-blogs-by-sap/odata-service-development-options/ba-p/13359604"
Wikipedia = "https://en.wikipedia.org/wiki/Open_Data_Protocol"
"SAP Note" = "https://launchpad.support.sap.com/#/notes/2485370"

[config]
label = "OData v2"
ring = "USE"
quadrant = "Technology"
active = true
moved = 0