[page]
title = "Build Workzone"
description = "Workzone is a central Fiori entry point in BTP. It can be used to integrated Fiori apps from on premise S/4HANA systems or from other sources (e.g. BTP) via CDM."
reason = "Workzone is the recommended technology for providing a central access point to Fiori apps accross multiple systems."
support = "Supported. recommended for central point of access for Fiori apps from multiple systems."

[links]
"SAP Fiori Deployment Options and System Landscape Recommendations" = "https://www.sap.com/docs/download/2018/02/f0148939-f27c-0010-82c7-eda71af511fa.pdf"
Blog = "https://community.sap.com/t5/technology-blogs-by-sap/sap-fiori-deployment-options-and-sap-fiori-front-end-server-strategy-update/ba-p/13444527#:~:text=SAP%20Fiori%20front%2Dend%20server%206.0%20%2D%20same%20as%20the%20predecessor,systems%20is%20the%20recommended%20setup."

[config]
label = "Workzone"
ring = "ADOPT"
quadrant = "Technology"
active = true
moved = 0
