[page]
title = "XSC"
description = "SAP HANA Extended Application Services Classic Model."
reason = "Successor is XSA, but apps should be developed either in ABAP/RAP or CAP."
support = "Successor is XSA"

[links]
"Documentation" = "https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abenxsc_glosry.htm"

[config]
label = "XSC"
ring = "STOP"
quadrant = "Technology"
active = true
moved = 0
