[page]
title = "Web Components"
description = "Enterprise-flavored sugar on top of native APIs!<br/><br/>Based on web standards - just HTML!<br/>- Future-proof.<br/>- Implement the SAP Fiori design language.<br/>- Feature-rich.<br/>- Secure, accessible, themeable, i18n-ready."
reason = "The new way for UI5 controls. Will substitute in the future the 'classic' ui5 controls."
support = "Recommended"

[links]
Documentation = "https://sap.github.io/ui5-webcomponents/"
"UI5 samples" = "https://ui5.sap.com/#/controls"

[config]
label = "Web Components"
ring = "ADOPT"
quadrant = "UI"
active = true
moved = 0
